### PR TITLE
Remove limit on number of results returned from `get_filter_values()`.

### PR DESCRIPTION
**Pull request by aaronweeden**
## Description

This PR removes the limit on the number of results returned from the `get_filter_values()` method. The limit was arbitrary and unnecessary.

## Tests performed

This PR adds a new regression test to make sure more than 10,000 (the previous limit) results are returned.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] `CHANGELOG.md` has been updated
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request
- [x] Running the automated tests (see `docs/developing.md`) produces no errors
- [x] Updates have been made to the `xdmod-notebooks` repository as necessary, and the notebooks all run successfully

### CODE REVIEW

**Comment by connersaeli** [comment]
I am having an issue with `tests/regression/test_datawarehouse_regression.py::test_describe_realms`. Data for that test seems to be edited in https://github.com/ubccr/xdmod-data/pull/14 to remove:
```
ResourceAllocations, Resource Allocations
```
However when I use the `describe_realms()` API call against production XDMoD, it appears that these lines are still present in the returned DataFrame. The test passes again once I add that line back into `tests/regression/data/realms.csv`. I can reproduce this for both `main` and this PRs branches. It could have been an oversight in my review and those lines might just need to be added back in.

It is probably out of scope for this PR, but I just wanted to mention with that being the only test breaking for this.

**Review by connersaeli — APPROVED** [review]
I was able to reinstall this branch of `xdmod-data` in a JupyterLab server. I already had a Notebook running that previously failed to find a specific filter for an Allocation. After reinstalling, I restarted the kernel and successfully managed to grab the information for the allocation.

I also ran all of the available tests. Specifically, the newly added `test_get_data_filter_user()` passed.

**Comment by aaronweeden** [comment]
> I am having an issue with `tests/regression/test_datawarehouse_regression.py::test_describe_realms`. Data for that test seems to be edited in #14 to remove:
> 
> ```
> ResourceAllocations, Resource Allocations
> ```
> 
> However when I use the `describe_realms()` API call against production XDMoD, it appears that these lines are still present in the returned DataFrame. The test passes again once I add that line back into `tests/regression/data/realms.csv`. I can reproduce this for both `main` and this PRs branches. It could have been an oversight in my review and those lines might just need to be added back in.
> 
> It is probably out of scope for this PR, but I just wanted to mention with that being the only test breaking for this.

@connersaeli thanks for reviewing, `ResourceAllocations` will appear if you don't have "User" set as your Top Role like it says to do in the testing instructions.

**Comment by connersaeli** [comment]
@aaronweeden That was the issue thanks! Sorry about that I elevated my Top Role for something else after I last tried this.

**Comment by aaronweeden** [comment]
> @aaronweeden That was the issue thanks! Sorry about that I elevated my Top Role for something else after I last tried this.

@connersaeli No problem, thanks again for reviewing.

**Pull request merged**
